####################################################################
# EXAMPLE INGEST PIPELINE CONFIGURATION TEMPLATE
#
# This file contains an example ingest pipeline configuration for
# raw buoy data provided in csv format.  See the data folder for
# the raw data used in this example.  See the
# ingest_pipeline_template.yml for an annotated description of
# configuration file parameters.
####################################################################
pipeline:
  type: Ingest

#-----------------------------------------------------------------
dataset_definition:  # Describes the dataset that will be produced
  attributes:
    title: Buoy Dataset for Buoy \#120
    description: "Example ingest dataset used for demonstration purposes.
      Split onto two lines"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    doi: 10.21947/1671051
    institution: PNNL
    code_url: https://github.com/clansing/tsdat/releases/tag/1.0
    location_id: humboldt_z05
    instrument_id: lidar_buoy
    data_level: b1
    location_meaning: Buoy is located of the coast of Humboldt, CA
    instrument_name: Wind Sentinel
    serial_number: '000011312'
    instrument_meaning: Self-powered floating buoy hosting a suite of meteorological and marine instruments.
    instrument_manufacturer: AXYS Technologies Inc.
    sampling_interval: 10 min

  dimensions:
    time:
        length: unlimited

  variables:

    time:
      input:
        # Name of the variable in the raw data
        name: DataTimeStamp
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: US/Pacific
            time_format: "%Y-%m-%d %H:%M:%S"
      dims: [time]
      type: long
      attrs:
        long_name: Time offset from epoch
        standard_name: time
        units: seconds since 1970-01-01T00:00:00
    
    # gill_horizontal_speed:  
    #   input: # From gill csv
    #     name: gill_hz_speed # Originally Horizontal Speed (m/s), manually renamed in custom hook
    #     units: m/s
    #   dims: [time]
    #   type: double
    #   attrs:
    #     long_name:  Horizontal wind speed
    #     units: m/s
    #     _FillValue: -9999
      
    # gill_horizontal_direction:  
    #   input: # From gill csv
    #     name: gill_hz_direction # Originally Horizontal Direction (deg), manually renamed in custom hook
    #     units: deg
    #   dims: [time]
    #   type: double
    #   attrs:
    #     long_name:  Horizontal wind direction
    #     units: deg
    #     _FillValue: -9999
    
    pressure:  
      input: # From pressure csv
        name: Barometric Pressure (mb)
        units: mbar
      dims: [time]
      type: double
      # required: true # TODO
      attrs:
        long_name:  Barometric pressure
        units: mbar
        fail_range: [0, 100]
        _FillValue: -9999
      
    relative_humidity:  
      input: # From rh csv
        name: Relative Humidity (%)
        units: '%'
      dims: [time]
      type: double
      attrs:
        long_name:  Relative humidity
        units: '%'
        fail_range: [20, 30]
        _FillValue: -9999

    sea_surface_temperature:  
      input: # From surfacetemp csv
        name: Surface Temperature (C)
        units: degC
      dims: [time]
      type: double
      attrs:
        long_name:  Sea surface temperature
        units: degC
        fail_range: [-30, 40]
        _FillValue: -9999

    air_temperature:  
      input: # From temperature csv
        name: Air Temperature (C)
        units: degC
      dims: [time]
      type: double
      attrs:
        long_name:  Air temperature
        units: degC
        _FillValue: -9999

    wind_horizontal_speed:  
      input: # From wind csv
        name: Horizontal Speed (m/s)
        units: m/s
      dims: [time]
      type: double
      attrs:
        long_name:  Horizontal wind speed
        units: m/s
        _FillValue: -9999
      
    wind_horizontal_direction:  
      input: # From wind csv
        name: Horizontal Direction (deg)
        units: deg
      dims: [time]
      type: double
      attrs:
        long_name:  Horizontal wind direction
        units: deg
        _FillValue: -9999

    latitude:  
      input: # From gps csv
        name: Latitude
        units: degree_N
      dims: [time]
      type: double
      attrs:
        long_name:  Latitude
        units: degree_N
        _FillValue: -9999
      
    longitude:  
      input: # From gps csv
        name: Longitude
        units: degree_E
      dims: [time]
      type: double
      attrs:
        long_name:  Longitude
        units: degree_E
        _FillValue: -9999

#-----------------------------------------------------------------
coordinate_variable_qc_tests:  # Define QC tests for coordinate variables

  missing:
    variables:
      - ALL
    operator:
      classname: tsdat.qc.operators.CheckMissing
    error_handlers:
      fail_pipeline:
        classname: tsdat.qc.error_handlers.FailPipeline

  monotonic:
    variables:
      - All
    operator:
      classname: tsdat.qc.operators.CheckMonotonic
    error_handlers:
      fail_pipeline:
        classname: tsdat.qc.error_handlers.FailPipeline

#-----------------------------------------------------------------
qc_tests:  # Define QC tests for non-coordinate variables

    missing:
        qc_bit: 1
        meaning: "Value is equal to _FillValue or NaN"
        assessment: Bad
        variables:
          - ALL  # keyword to apply test to all variables
        operator:
          classname: tsdat.qc.operators.CheckMissing
        error_handlers:
          # Replace any NaNs with _FillValue
          replace_with_fill_value:
            classname: tsdat.qc.error_handlers.RemoveFailedValues

    fail_min:
        qc_bit: 2
        meaning: "Value is less than the fail_range."
        assessment: Bad
        variables:
          - ALL
        operator:
          classname: tsdat.qc.operators.CheckFailMin

    fail_max:
        qc_bit: 3
        meaning: "Value is greater than the fail_range."
        assessment: Bad
        variables:
          - ALL
        operator:
          classname: tsdat.qc.operators.CheckFailMax

    warn_min:
        qc_bit: 4
        meaning: "Value is less than the warn_range."
        assessment: Indeterminate
        variables:
          - ALL
        operator:
          classname: tsdat.qc.operators.CheckWarnMin

    warn_max:
        qc_bit: 5
        meaning: "Value is greater than the warn_range."
        assessment: Indeterminate
        variables:
          - ALL
        operator:
          classname: tsdat.qc.operators.CheckWarnMax

    valid_delta:
        qc_bit: 6
        meaning: "Difference between current and previous values exceeds valid_delta."
        assessment: Indeterminate
        variables:
          - ALL
        operator:
          classname: tsdat.qc.operators.CheckValidDelta
          parameters:
            dim: time
